some completion foo, command-not-found wiring

diff --git a/shell/bash/bashrc b/shell/bash/bashrc
--- a/shell/bash/bashrc
+++ b/shell/bash/bashrc
@@ -33,12 +33,26 @@ shopt -s histreedit
 shopt -s histverify
 shopt -s lithist
 
+
+## History
 HISTCONTROL=ignoreboth:erasedups
 HISTFILE=~/.bash_history
 HISTSIZE=10000
 HISTFILESIZE=10000
 unset MAILCHECK
 PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"
+
+
+## command-not-found
+command_not_found_handle() {
+  if [[ -x /usr/lib/command-not-found ]]; then
+    /usr/lib/command-not-found -- "$1"
+    return $?
+  else
+    printf '%s: command not found\n' "$1" >&2
+    return 127
+  fi
+}
 
 
 ## Prompt
diff --git a/shell/zsh/zshrc b/shell/zsh/zshrc
--- a/shell/zsh/zshrc
+++ b/shell/zsh/zshrc
@@ -18,28 +18,43 @@ if [[ ! -o interactive ]]; then
   return
 fi
 
-## History
-setopt autopushd
-setopt pushd_ignore_dups
 
+## History
 export HISTFILE=${HOME}/.zsh_history
 export HISTSIZE=10000
 export SAVEHIST=10000
 setopt append_history
+setopt autopushd
 setopt extended_history
 setopt hist_ignore_all_dups
-setopt inc_append_history
-setopt share_history
 setopt hist_reduce_blanks
 setopt hist_verify
+setopt inc_append_history
+setopt pushd_ignore_dups
+setopt share_history
+
+
+## command-not-found
+command_not_found_handler() {
+  if [[ -x /usr/lib/command-not-found ]]; then
+    /usr/lib/command-not-found -- "$1"
+    return $?
+  else
+    printf '%s: command not found\n' "$1" >&2
+    return 127
+  fi
+}
+
 
 ## Shush
 setopt nobeep
+
 
 ## make sure run-help is available
 unalias run-help 2>/dev/null
 autoload run-help
 export HELPDIR=/usr/share/zsh/help
+
 
 ## Editor
 bindkey -e
@@ -58,6 +73,10 @@ bindkey '^[s' insert-sudo
 
 ## Prompt
 . "${ZDOTDIR}"/prompt/all.zsh
+
+
+## Completions
+. "${ZDOTDIR}/completion"
 
 
 ## zplug
